### ISSUE TITLE
[Proposal] Add NodeJS 8 support to templates

### ISSUE THREAD

**Issue by austinfrey** [openfaas/faas-cli#212]
NodeJS 8 has reached LTS status. This brings some significant usability upgrades. Should we maintain support for both LTS versions?

## Possible Solution

Add additional templates based on current NodeJS 6 template, with support for NodeJS 8. Functionality should remain the same by simply bumping the base image to NodeJS 8 but this would need testing to confirm.

## Context

Adding NodeJS 8 support makes working with asynchronous functions much much easier. Async/Await is native and does not require a flag.

Raising this issue for discussion on whether OpenFaaS should support 2 NodeJS versions or simply one. If only one, which should it be.

**Comment by austinfrey** [comment]
Derek add label: proposal

**Comment by BurtonR** [comment]
@austinfrey I don't think that there is a need for maintaining previous versions of a language in the templates. The templates are for new functions being created. I would think we would advocate for the latest features and security updates of what we provide in the templates.

Creating a function using a previous version of a language is still supported with the Dockerfile language option.

**Comment by rgee0** [comment]
A consideration here should be backwards compatibility - can we assure that existing code will not break on a new template?

I think that now we have the custom templates feature merged we could have a model where old templates are made available through a template archive.  There isn't any additional work / maintenance involved here other than moving the existing template to the archive repo once we have moved to a new version.  We would then have a reference point to refer people to should difficulties with newer templates be experienced.

**Comment by BurtonR** [comment]
Forgive me if I'm missing something, but updating the templates' version _shouldn't_ affect any existing code. This is only when calling `faas-cli new function_name --lang node`. Existing code would either be already written out in an existing function, or copy/paste into the new template.

Copying existing code into a new template may cause some issues as there are some breaking changes [here](https://nodejs.org/docs/v8.9.1/api/deprecations.html#deprecations_list_of_deprecated_apis). However, this should be considered writing a new function. If the code that was copied over is not compatible, it should be updated, or change to use the Dockerfile template and defining the version that you need there.

I do like the idea of a "template archive" so that there can be many options with different versions available, but I think the main templates should be kept up with the latest (stable) versions to remain relevant.

**Comment by austinfrey** [comment]
closing in favor of @BurtonR 's pr  #212

**Comment by johnmccabe** [comment]
@austinfrey do we need a new issue opened to track @BurtonR's PR? Or is this still valid?

**Comment by austinfrey** [comment]
@johnmccabe I'll re-open if want to track that PR here.
