### ISSUE TITLE
Define build-args in yaml file

### ISSUE THREAD

**Issue by itscaro** [openfaas/faas-cli#262]
Currently there are only two build-args passed to docker build using ENV variables (http_proxy, https_proxy), in order to generalise and to permit sharing some args between functions or adding args to a function, we might have build-args defined in Yaml file as below.

There are two levels, top-most are build-args sharing between all builds and build-args attached to a specific function. If a build-arg defined both in these two levels, the build-arg attached to a function takes the priority.

```
provider:
  name: faas
  gateway: http://localhost:8080

docker:
  build-args:
    ARG1:
    ARG2:

functions:
  test:
    lang: node
    handler: ./test
    image: test
    docker:
      build-args:
        ARG1:
        ARG3:
```

## Expected Behaviour
Dockerfile can get args defined in Yaml, so that build are more customisable.

## Current Behaviour
Only two build-args are possible (http_proxy and https_proxy)

This proposal comes from #255

**Comment by itscaro** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Interesting idea - this is for people to define passwords / SSH keys right? How would these be picked up though with a standard template?

**Comment by alexellis** [comment]
@ryanfields is this what you need for #255 ?

**Comment by ryanfields** [comment]
@alexellis It would be a functional fix, but not a very convenient one and prone to causing developer confusion.  I'm really still looking for a way to get key files and arbitrary shell scripts into the faas-cli build directory before it executes the Docker build step, and my very strong opinion is that needs to be done during build.go's createBuildTemplate call (with the files specified in the YAML stack file to be copied into that the build dir created by createBuildTemplate.)

I _do_ think the proposal here has value though.  If I could get the arbitrary file support from createBuildTemplate, I could then use this build-args fix to set flags that my arbitrary shell scripts can flag on.

**Comment by alexellis** [comment]
We should not reference "docker" as a sub-node of the YAML file. The faas-cli exists to abstract this level of detail away - we don't want to reinvent the CLI.

**Comment by ryanfields** [comment]
What I like about having build args (which are a Docker-specific feature at the moment) provided in the YAML file is that they become documented in the same place they are applied.  There's no requirement that a dev remember to provide them on every run of the CLI.  There's no need to write extra scripts that exist solely for the purpose of remembering to pass configuration args to the CLI.

You could abstract build args, but other container tooling may not include a comparable feature, introducing a "not supported by the underlying tooling" class of error.  It seems to me that having an escape hatch in the YAML to reach specific features of the underlying tooling is a positive.  It makes it very obvious to other devs, just by reading the YAML, that Docker-specific features are in use.  In a future hypothetical switch away from Docker to something else, there's an immediately visible, self-documented warning there in the YAML that certain features need to be considered before making the switch.

Abstractions are nice, but when they're abstracting a class of tooling that doesn't adhere to an API standard, they need escape hatches.  Otherwise, you end up in a lowest-common-denominator situation where you can only support features that exist universally across all of the underlying tools you support (and run into big challenges if any of those tools drop or significantly alter a "common" feature in the future.)

**Comment by s8sg** [comment]
After going through the previous comments, what I like the most about the build args is to provide a defined argument with variable set of values. The `build args` are very useful in a environment when the build process is dependent on the argument. For example in an automated build process the function needs to pull the dependent version of application, where we can provide the version via `--build-arg`. Or using a APIKEY to pull some certain commits where the `APIKEY` is a variable. In current situation as I understand that we have to change the `Dockerfile` each time or do some other hacks by providing the version via some files in the build context; which is not efficient. For me the `stack.yml` is the function definition like `Dockerfile` in docker. A variable argument should be defined as: 
```yml
functions:
  test:
    lang: node
    handler: ./test
    image: test
    args:
      ARG1:
      ARG3:
```
Here the `args` must be independent of the implementation type. For Dockerfile we can convert it to the `--build-args`. As we know we need to define `ARG` in dockerfile, it means the resulted Dockerfile can be generated based in the `args` defined in the stack.yml. 
for:
```yml
    args:
      ARG1:
      ARG3:
```
The generated Dockerfile would have: 
```dockerfile
ARG ARG1
ARG ARG2
```
For the fass-cli build it can be passed as:
```bash
faas-cli build -f https://domain/path/myfunctions.yml --arg ARG1=$VALUE
``

**Comment by iyovcheva** [comment]
Derek add label: help wanted

**Comment by alexellis** [comment]
This proposal is not approved for work at this stage.

**Comment by ryanfields** [comment]
@alexellis I can work with that, yes.

**Comment by alexellis** [comment]
Glad to hear it @ryanfields - the work will be starting under #363 and contributions are welcome (if you want to write some code towards it) as well as helping us validate we're doing this the way that helps.

**Comment by BurtonR** [comment]
Looks like this issue got lost in all the other issues/PRs around this feature.
#364 resolves this and has been merged.

**Comment by BurtonR** [comment]
Derek close
