### ISSUE TITLE
Tests broken by recent PRs to master

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#299]
It looks like the tests were broken by recent commits to master. Unfortunately the error messages could be better too and don't give a lot away.

I've started debugging this and saw that there is an unexpected exit code 1 with one of the `git` commands. This will block fixes and releases from GitHub so we need to resolve as soon as we can.

@itscaro @LucasRoesler please could one or both of you check this out and see what we need to do for a fix?

Thanks

![screen shot 2018-01-25 at 11 10 43 pm](https://user-images.githubusercontent.com/6358735/35417668-5aa3ec44-0226-11e8-8bb2-f41cc0d5a0f1.png)

**Comment by BurtonR** [comment]
I started to look in to this, but wasn't able to pinpoint the code causing the troubles.
Here's what I did find:
The `fetch_templates_test.go` is calling the commands with missing parameters causing the `Invoke` command to error out

The 3 errors that are being returned during the tests:
`Error: please provide a valid --image name for your Docker image`
`Error: please provide the full path to your function's handler`
`Error: please provide the deployed --name of your function`

**Comment by itscaro** [comment]
@alexellis the screenshot is on local right? on Travis I do not see errors.

can you run `git submodule update --init --recursive`
![image](https://user-images.githubusercontent.com/266018/35433427-abb4fbde-0283-11e8-8b90-6b819b49d899.png)

**Comment by BurtonR** [comment]
Running the `git submodule update --init --recursive` worked for me. All tests passing locally 👍

**Comment by LucasRoesler** [comment]
perhaps this should be included in the makefile for the `test-unit` command?

**Comment by itscaro** [comment]
@LucasRoesler agree, cf #300

**Comment by alexellis** [comment]
Still not comfortable with this. Is there another way we can do this without a sub-module?

**Comment by LucasRoesler** [comment]
The only requirement is that there is a git repo somewhere on disk, one or two functions should work for my tests.  In my original tests, I was just cloning the repo and then cleaning it up after.  I used subtests so that I could group tests that needed the repo into a single test, allowing me to clone it once and `defer` the cleanup to the test end.

I think the benefit of the submodule is that it is harder to generate a dirty git state and easier to share it between multiple tests, i.e. less chance of "clone/cleanup/clone/cleanup repeat" slowing the tests down if someone else does the same thing.  

We could easily call the sub-module init from the tests, to make it even easier to deal with.

**Comment by itscaro** [comment]
@alexellis @LucasRoesler In the latest change to the PR #300, I include directly two template dockerlang & ruby in testdata. during the test, I git init to have a local repo for testing

**Comment by LucasRoesler** [comment]
@itscaro I like this approach, it is simple, clean, easy to maintain, and easy to test against
