### ISSUE TITLE
0.6.2: `faas-cli store deploy function --gateway` gives error

### ISSUE THREAD

**Issue by vielmetti** [openfaas/faas-cli#315]
## Expected Behaviour

Expected: you should be able to specify --gateway to point your faas-cli at a local gateway for all `faas-cli store` operations.

## Current Behaviour

This change was introduced in 0.6.2:

https://github.com/openfaas/faas-cli/commit/9abc0880aa84cd1497a50ea2d55eb4af6fc38422#diff-4d8c2dcb33807ea71d97dffb92481be6

It removes the `-g` flag that had pointed to the store, replacing it with a `-u` flag, but not restoring the gateway function.

## Possible Solution

Put gateway logic into store function.

## Steps to Reproduce (for bugs)
1. using `brew` install version 0.6.2

```
% faas-cli store deploy Colorise --gateway http://127.0.0.1:31112/
Unknown flag: --gateway
```

## Context

Workaround is deploying function via UI, but that doesn't let me set environment variables.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):

Docker 18.02.0-ce-rc2 darwin/amd64

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS):

Darwin Eds-MacBook-Pro.attlocal.net 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

* Link to your project or a code example to reproduce issue:

**Comment by rgee0** [comment]
I think possible fixes would be in https://github.com/openfaas/faas-cli/blob/fabe0853628d6750036570dbd85cb0f2b0f04559/commands/store.go#L35

Either `storeCmd` becomes `storeDeployCmd` and then `gateway` will only be expected in deploy

OR

Change `Flags()` to `PersistentFlags()` so that its accepted (but not necessarily used) by all sub commands.

I have tried both and they seem to work.  Haven't PR'd it as the tests are failing (in seemingly unrelated areas) - I think they're failing on master too tho?

**Comment by rgee0** [comment]
@itscaro seems to be fixing this in #309
