### ISSUE TITLE
Question on Golang package structure

### ISSUE THREAD

**Issue by hypnoglow** [openfaas/faas-cli#324]
I've tried some options and could not figure out how to build a golang function containing subpackages. My example function repository: https://github.com/hypnoglow/somefunc

The only successful yet not convenient option I found is just to vendor all subpackages so the function contains only `vendor` folder and not subpackages. 

## Expected Behaviour
Building a goland function with subpackage succeeds.

## Current Behaviour
Building a golang function with subpackage fails.

## Possible Solution
I think Dockerfile should somehow respect GOPATH instead of [copying source code](https://github.com/openfaas/faas-cli/blob/master/template/go/Dockerfile#L9) to `/go/src/handler` directory.

## Steps to Reproduce (for bugs)

1. `git clone https://github.com/hypnoglow/somefunc.git && cd somefunc`
2. `faas-cli build -f hello.yml`

<details/>
  <summary>Failure log</summary>
<pre>
ή faas-cli build -f hello.yml
[0] > Building hello.
Clearing temporary build folder: ./build/hello/
Preparing ./hello/ ./build/hello/function
Building: hello with go template. Please wait..
Sending build context to Docker daemon  8.192kB
Step 1/17 : FROM golang:1.8.3-alpine3.6
 ---> fd1ada53b403
Step 2/17 : RUN apk --no-cache add curl     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/openfaas/faas/releases/download/0.6.9/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache
 ---> Using cache
 ---> d5ea7690e104
Step 3/17 : WORKDIR /go/src/handler
 ---> Using cache
 ---> 72ad5bd7b0c2
Step 4/17 : COPY . .
 ---> 23abb77adaec
Step 5/17 : RUN test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }
 ---> Running in 795a8e0bf697
Removing intermediate container 795a8e0bf697
 ---> 6872cc86af7f
Step 6/17 : RUN CGO_ENABLED=0 GOOS=linux     go build --ldflags "-s -w" -a -installsuffix cgo -o handler . &&     go test $(go list ./... | grep -v /vendor/) -cover
 ---> Running in d920b17b3a74
function/handler.go:6:2: cannot find package "github.com/hypnoglow/somefunc/hello/sub" in any of:
	/usr/local/go/src/github.com/hypnoglow/somefunc/hello/sub (from $GOROOT)
	/go/src/github.com/hypnoglow/somefunc/hello/sub (from $GOPATH)
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux     go build --ldflags "-s -w" -a -installsuffix cgo -o handler . &&     go test $(go list ./... | grep -v /vendor/) -cover' returned a non-zero code: 1
2018/02/15 23:14:04 ERROR - Could not execute command: [docker build -t hello .]
</pre>
</details>

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
ή docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
No, I execute `faas-cli build` locally.

* Operating System and version (e.g. Linux, Windows, MacOS):
macOS

* Link to your project or a code example to reproduce issue:
https://github.com/hypnoglow/somefunc

**Comment by alexellis** [comment]
Derek edit title: Question on Golang package structure

**Comment by alexellis** [comment]
Derek set title: Question on Golang package structure

**Comment by alexellis** [comment]
Hi,

Subpackages are supported and they don't have to go into the vendor directory. The path in the function isn't the same as the path in your GitHub account - that's the reason why it may be complaining of not finding your subpackage.

I'll try to make an example for you, but in the meantime look at the template folder's Dockerfile for a clue about the GOPATH you'll have relative in the container (function).

**Comment by alexellis** [comment]
@hypnoglow here's an example using submodules. As I mentioned above the GOPATH is relative to where the handler exists in the function's filesystem.

https://github.com/alexellis/submodule-go-example

Good luck

**Comment by alexellis** [comment]
Derek close: resolved

**Comment by hypnoglow** [comment]
>  The path in the function isn't the same as the path in your GitHub account - that's the reason why it may be complaining of not finding your subpackage.

Actually it IS the correct and idiomatic package path.

> @hypnoglow here's an example using submodules. As I mentioned above the GOPATH is relative to where the handler exists in the function's filesystem.

And [this](https://github.com/alexellis/submodule-go-example/blob/master/sub/handler.go#L5) path is correct only inside docker image but absolutely not correct package path relative to developer's GOPATH. 

---

I think you understand what I mean. By forcing package path to start with `handler/function` and not with `github.com/foo/bar` you are breaking Golang idiomatic GOPATH import system and developer experience. Is this policy on openfaas golang functions desirable?

**Comment by hypnoglow** [comment]
ping @alexellis 

I don't see why do you always close issues when it is actually not resolved yet from the submitter point of view.

**Comment by alexellis** [comment]
I am not aware of any FaaS projects which allow a custom sub-package (FYI: some don't even allow multiple files).

The experience for the handler file is consistent with the default Go user-experience but you are right to say *it is different for a sub-module*. The sub-module will have to take a prefix for the time-being since Docker needs to add all the function code to a standard location.

The issue is closed because a resolution has been given and the question was answered. Here are 5 options for you:

1. Vendor any sub-modules

2. Use a single module (this is meant to be a function handler)

3. Use the sub-package using the namespace prefix given above `handler/function/`

4. Create your own Go template. You can [fork the Go template](https://github.com/openfaas/templates/tree/master/template/go) and edit it to see if you can have it work the way you want.

5. Use the Dockerfile language type - this allows you to use your own Dockerfile and then customise the function however you like.

Can you see any alternative solution for your request on sub-modules? Perhaps you would like to contribute towards a solution if this is an important use-case for you?

**Comment by hypnoglow** [comment]
Thank you for your response.

Options 4 and 5 are pretty viable and enough. But the user experience with go template actually can be a bit improved.

> Can you see any alternative solution for your request on sub-modules? Perhaps you would like to contribute towards a solution if this is an important use-case for you?

I will try to figure out some solution and create a new issue if I found any that does not break compatibility.

**Comment by nicholasjackson** [comment]
I generally see packages for functions as a code smell, when I start to need to add additional packages I see this that my function is getting to big.  A function should be a single unit of work and is intended to be simple and straight forward.

That said it is useful to move code into sub-files to keep things separate, and for dependency isolation which is useful for testing.

I mainly follow the following two strategies:

1. External package and vendor with Dep
2. Additional go file in the function package

If this is not working for you another option is to create your package in the functions `vendor` folder, because GOPATH looks their for an import first and because this folder is copied to the Docker build it works fine for both local testing and docker builds.  Again tho, if your function is large then consider whether it is actually a function or should be an independent micro service.
