### ISSUE TITLE
Proposal: support docker build args via "faas-cli build" flags.

### ISSUE THREAD

**Issue by hypnoglow** [openfaas/faas-cli#325]
The proposal is to add a possibility to pass build args to an underlying "docker build" process. This is kind of related to #262 but I propose to add command-line flags to "faas-cli build" command.

## Expected Behaviour
1) Define a build arg in Dockerfile.
    <details>
    <pre>
    FROM golang:1.9.2 as builder
    ARG FOO=defaultValue
    RUN echo $FOO
    </pre>
    </details>
2) Run `faas-cli build -f my-func.yaml --args FOO=bar`. The FOO argument is actually passed to `docker build` command as `--build-arg` flag.

3) Output:
    <details>
    <pre>
    faas-cli build -f my-func.yml --args FOO=bar
    2018/02/16 16:47:54 No templates found in current directory.
    2018/02/16 16:47:54 Attempting to expand templates from https://github.com/openfaas/templates.git
    2018/02/16 16:47:55 Fetched 11 template(s) : [csharp dockerfile go go-armhf node node-arm64 node-armhf python python-armhf python3 ruby] from https://github.com/openfaas/templates.git
    [0] > Building my-func.
    Building: my-func with Dockerfile. Please wait..
    Sending build context to Docker daemon  86.02kB
    Step 1/3 : FROM golang:1.9.2 as builder
     ---> 138bd936fa29
    Step 2/3 : ARG FOO=defaultValue
     ---> Running in 88983c7e27d7
    Removing intermediate container 88983c7e27d7
     ---> ee0d598870c7
    Step 3/3 : RUN echo $FOO
     ---> Running in 751d526d0828
    bar
    Removing intermediate container 751d526d0828
     ---> 273e36de5a09
    Successfully built 273e36de5a09
    Successfully tagged my-func:latest
    Image: my-func built.
    </pre>
    </details>

## Current Behaviour
Docker build args are not supported.

## Context
This can solve issues like [this](https://github.com/openfaas/faas-cli/issues/324#issuecomment-366217128), if we can use build arguments in openfaas templates.

**Comment by alexellis** [comment]
Hi Igor,

I've read your proposal and compared it to #262 - as far as I can tell it's a duplicate but you specify wanting to use CLI arguments and @itscaro specifies using YAML.

If we make this change then it will need to be supported via the CLI and via YAML so I'm going to close your issue and reference it on #262. Please feel free to mention your request for CLI support there or +1 the issue.

My concern in passing arbitrary build flags to the OpenFaaS template is the following:

* the template becomes less deterministic
 * more opportunities for hard-to-reproduce bugs
 * different behaviour on one machine vs another depending on flags
* tightly couples the function to the underlying Docker build
  * the users now need white-box knowledge of what is inside the templates in order to know what build-args to pass
  * users are likely to want to change the available build-args to make the templates more configurable, this will add complexity to the standard templates

With those concerns in mind we should be careful about injecting run-time parameters into the Docker build. Maybe if we take a step back and analyze the problem that this acts to solve we could consider whether other approaches exist?

**Comment by hypnoglow** [comment]
Hmm, from one point of view these are definitely interesting concerns that should be analyzed. 

But, I think all these decisions were already made when docker implemented build arguments feature. Refs: [1](https://github.com/moby/moby/pull/9176), [2](https://github.com/moby/moby/issues/14634) and others. And, as **openfaas** uses docker as a container implementation, but tries to abstract it away, maybe can we have a specific group of CLI flags that are related to docker and passed directly to the docker CLI? 

As an example that comes to mind: `minikube start` supports `--container-runtime` flag (`the container runtime to be used`) and `--docker-opt` flag (`Specify arbitrary flags to pass to the Docker daemon. (format: key=value)`). I'm not saying that this is the only right decision. But at least it provides the flexibility in docker usage.

Another weird thing to notice that openfaas CLI already supports docker-specific flags like `--no-cache` and `--squash`.

Just thinking out loud.

**Comment by alexellis** [comment]
Derek close: duplicate

**Comment by alexellis** [comment]
@hypnoglow let's continue discussion on the original issue.
