### ISSUE TITLE
Unable to push image using faas-cli

### ISSUE THREAD

**Issue by CentricStraaten** [openfaas/faas-cli#326]
I created an OpenFaas function. After the build i try to push it to my docker repository:
`faas-cli push -f demo.yml`

I receive an error message

```
[33m[0] > Pushing cenceptdemo.
[0mThe push refers to repository [docker.io/library/demo]
611ad21ee6ff: Preparing
faec93b185fb: Preparing
f9d2d3e199b9: Preparing
9eec8925915b: Preparing
6c69f7ce3401: Preparing
e27a10675c56: Preparing
e27a10675c56: Waiting
faas-cli : denied: requested access to the resource is denied
At line:1 char:1
+ faas-cli push -f demo.yml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (denied: request...ource is denied:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
2018/02/17 09:39:42 [31mERROR - Could not execute command: [docker push demo][0m
```
Docker is running and i am logged in. I can push containers using the docker push command.

**Comment by alexellis** [comment]
Hi @CentricStraaten,

The error is quoted above it says the following:

```
faas-cli : denied: requested access to the resource is denied
```

In order to push your image to the Docker Hub (the default registry) you'll have to edit your YAML file and fill in your user account. Mine is alexellis2 so I'd put `image: alexellis2/demo`.

```
[0mThe push refers to repository [docker.io/library/demo]
```

^ This bit is showing that you didn't add a prefix, so you have access denied due to trying to push to the Docker library account. Please edit your YAML file and try again. 👍

**Comment by alexellis** [comment]
Derek close: resolved. Please feel free to keep commenting.

**Comment by marlexct** [comment]
Hello, I was trying to build a function, Im usinf Kind into a AWS EC2 ubuntu machine. I get the following message:

root@ip-172-31-12-150:~/dev/kind-blog# faas-cli push -f openfaas-loves-crds.yml
[0] > Pushing openfaas-loves-crds [marlexct12/openfaas-loves-crds:latest].
The push refers to repository [docker.io/marlexct12/openfaas-loves-crds]
An image does not exist locally with the tag: marlexct12/openfaas-loves-crds
