### ISSUE TITLE
Arch Linux release stale - 0.4.30

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas-cli#348]
## Expected Behaviour

Arch Linux release package should track the current project release or be removed from AUR.

## Current Behaviour

Last Arch Linux release was `0.4.30`.

## Possible Solution

Ping @rawkode to see if he intends to continue as Arch Linux PKGBUILD maintainer, if not pass on responsibility to the project.

## Steps to Reproduce (for bugs)

- https://aur.archlinux.org/packages/openfaas-cli/
- https://aur.archlinux.org/cgit/aur.git/?h=openfaas-cli

<img width="1327" alt="screen shot 2018-03-07 at 00 58 37" src="https://user-images.githubusercontent.com/83862/37067652-bd09cb2e-21a2-11e8-886d-211ae3327313.png">

## Context

Need all releases to be consistent.

## Your Environment

n/a

**Comment by alexellis** [comment]
> Arch Linux release package should track the current project release or be removed from AUR.

I'd agree with this statement - we have to keep third-party packages in sync. 

Ping @rawkode - please could you take a look?

**Comment by alexellis** [comment]
From David via DM: "I have disowned the package and it cannot be deleted"

Not great IMHO :thinking:

Not sure what we can do from here so I'll close the issue. If someone finds this via Google, you're welcome to take over the maintenance of the package.

**Comment by rawkode** [comment]
Unfortunately, I am getting married this weekend; so my availability to contribute has been non-existent, as planning a wedding isn't exactly trivial.

I did attempt to upgrade the package, but the dependency management changed from vndr to dep and the PKGBUILD changes weren't as simple as I expected; so I had to disown so that someone else can pick it up.
