### ISSUE TITLE
Proposal: Add support for PHP

### ISSUE THREAD

**Issue by itscaro** [openfaas/faas-cli#55]
Expected Behaviour

Add template for PHP in order to support built-in build for PHP

Your Environment

Docker Version: 17.06.1-ce
Go version: go1.8.3
OS/Arch: linux/amd64

**Comment by alexellis** [comment]
Hi @itscaro thanks for trying OpenFaaS.

The idea behind opening an issue is for discussion more than process. I had a few questions.

Is PHP a language you are going to need to work with? I ask because each new language added as an official template needs consideration as we'll have to support it in the project.

**Core supported version**

I also wonder what PHP version people are most likely to need?

**Dependency management**

Within Node, CSharp, Python and Ruby we have a way of specifying and managing additional dependencies. This seems like a core use-case for templates - i.e. adding a Gem or `pip` module.

Have you thought about how to express and manage dependencies for the PHP template?

**Comment by itscaro** [comment]
**Is PHP a language you are going to need to work with?**: I work mostly with PHP and Go.

**Core supported version**: I think PHP 7 is ok for faas. Older versions of PHP are still widely used, but for new developments in my environment we opt for latest version of PHP (7.x)

**Dependency management**: It's Composer for PHP libraries, there are also extensions which need to be compiled and added through building steps in docker. In some cases, PHP libraries depend on PHP extensions, in this case it maybe better to build the image with Dockerfile instead.
I thought of implementing composer too, but I started with a simpler template.

**Comment by alexellis** [comment]
Thanks for the info. I think the most basic template needs to have dependency management to follow the style and experience of the project.

**Comment by itscaro** [comment]
I've just updated the template. Composer is used to handle PHP-library dependencies. Other PHP have extensions which need to be compiled can be add through php-extensions.sh which is a shell file called by Docker build.

**Comment by alexellis** [comment]
Please can you raise a PR with a table of community templates starting with yours?

I'll merge after #201 

| Language  | Author   | URL  |
|---|---|---|
| PHP | @itscaro   | https://github.com/itscaro/openfaas-template-php/  |
| PHP5 | @itscaro   | https://github.com/itscaro/openfaas-template-php/  |

@johnmccabe 👍 👎 ?

**Comment by johnmccabe** [comment]
Big 👍

**Comment by alexellis** [comment]
Awesome. Let's do it then.

**Comment by withinboredom** [comment]
I was just wondering about this! Huge thanks to @itscaro for getting this together! 👍

**Comment by alexellis** [comment]
This is moving over to #220 #201
