### ISSUE TITLE
r E: Unable to locate package eclipse-jee The command '/bin/sh -c apt-get install -y eclipse-jee' returned a non-zero code: 100

### ISSUE THREAD

**Issue by nicolasguelfi** [openfaas/faas-cli#602]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Derek add label: invalid

**Comment by alexellis** [comment]
Closing since the template has not been filled out with enough information to assist you. 

Happy to reopen if you can will out the while issue template and report your issue constructively. I suspect this may be a support request rather than a bug, in which case sign up to Slack: https://docs.openfaas.com/community

Alex
