### ISSUE TITLE
How do I share host files when I deploy a  docker container?

### ISSUE THREAD

**Issue by Littermonkey** [openfaas/faas-cli#611]
## Current Behaviour

I try to mount host files to docker container, but there is not  in faas-cli help doc.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I use faas-cli deploy many docker containers . how do i share the host files to them. 
## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.8.1
* Docker version ( Full output from: `docker version` ):
18.06.1-ce
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
docker swarm 
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux (Ubuntu 18.04.1 LTS)
* Link to your project or a code example to reproduce issue:

**Comment by kturcios** [comment]
Hi @Littermonkey ,

I believe what you are intending to do is an anti-pattern for the project because functions are intended to be short-lived and stateless. You can use an external object storage for your functions such as S3 or Minio. 

Read more about it [here](https://github.com/openfaas/faas/issues/320).

**Comment by alexellis** [comment]
Derek close: resolved
