### ISSUE TITLE
[Node12 template] Unable to push "build" folder into container image

### ISSUE THREAD

**Issue by Janaka-Steph** [openfaas/faas-cli#803]
Working on a React.js app with Node12 template. The template's Dockerfile doesn't contain a build step (`npm run build`). The recommended way is to build locally, then `faas-cli up` should copy the source code and the React "build" folder into the container image. The issue is that the "build" folder is skipped. See those lines: https://github.com/openfaas/faas-cli/blob/f9a4019176bf4ff0c2c3e7e39c8d2c01b3ddb94a/builder/build.go#L213-L215

```
$ faas-cli up
[0] > Building bitcoin-studio-client.
Clearing temporary build folder: ./build/bitcoin-studio-client/
Preparing: ./client/ ./build/bitcoin-studio-client/
Skipping "build" folder
...
```

## Expected Behaviour

The React.js build folder should be copied into the container image.

## Current Behaviour
The build folder is skipped.

## Possible Solution
Maybe check that "build" direct subdirectory is not named as the function name, so that we can distinguish between react.js "build" folder and faas-cli "build" folder.

## Steps to Reproduce (for bugs)
Here is a minimal repo where you can reproduce the issue: https://github.com/Janaka-Steph/openfaas-node12-react

Step to reproduce:

In one tab
 - kubectl port-forward svc/gateway -n openfaas 8080:8080

In a other tab
 - cd function
 - npm i
 - npm run build
 - cd ..
 - faas-cli up

**Comment by Waterdrips** [comment]
thanks @Janaka-Steph 

The build folder is excluded because in the faas-cli we exclude "build" and "function" folders 
https://github.com/openfaas/faas-cli/blob/49d9f888a6e06b4e2cfdf542cfbf6dde2ebed7d7/builder/build.go#L213-L215

This is due to these folder names being used as part of the OpenFaaS image build process. 



For deploying a "production" react app I would suggest using a Dockerfile based on nginx or similar and to include only the build folder rather than using node. This would lead to drastically smaller images, with much smaller attack surface. 

```Dockerfile
# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install 
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

```

(from [this post](https://mherman.org/blog/dockerizing-a-react-app/))

**Comment by Janaka-Steph** [comment]
Thank you for your suggestion, I am exploring this way. But the exact same issue remains, unless we have a `npm run build` step in the Dockerfile, which I thought was bad practice.

**Comment by Waterdrips** [comment]
It doesn't make sense to run `npm run build` because this is a generic node12 template not everyone will want to use that to build and deploy their code. 

having a `npm run build` in a dockerfile for bundling a production build of a react app is fine.
You could fork the node template for now and add the `npm run build` step in to suit your needs?


For clarification on the `issue`:

The issue is that if a user has a `build` or `function` directory inside their function's directory then it will be excluded from the final image.
