### ISSUE TITLE
Proposal: Allow customizing the location that the cli config is stored

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#832]
When working with @utsavanand2 on his upcoming blog post about Github Actions, it became clear that it would be really helpful to allow customizing the location of the CLI config file. Some initial work is done in #831 that will make the CLI much easier to use in CI environments. But i want to propose some larger changes

1) we could add support for a new env variable `OPENFAAS_CONFIG`. This would be the path to the config directory. If it is empty then it is equivalent to `$HOME/.openfaas` which is the current behavior. This makes the change backwards compatible. 
    Supporting this variable would allow the user to place the config in any location that is needed. In CI it could be preferable that this is in the current working directory. Or, a user might have a CI system running in k8s and want to store and then mount the secret with the configuration. The user can then mount anywhere, e.g. `/openfaas` and then set the `OPENFAAS_CONFIG` to for simplicity
2) Alternatively or additionally, we should consider if we want to support the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) We currently write to `~/.openfaas` but if we want to be compatible with XDG, it _should_ be `~/.config/openfaas`. To implement this, we would want to use a library like https://github.com/adrg/xdg 
    **Note:** Changing this on it's own would _not_ be backwards compatible, but i have a third proposal that would provide that compatibility.   
3) The CLI can look for configuration folder in multiple locations in order: 
    1. look for (hidden) directory `.openfaas` in the current directory 
    2. look for the config file in  `OPENFAAS_CONFIG`
    3. look for directory `openfaas` in `XDG_CONFIG_HOME`
    4. look for the config directory `~/.openfaas` 
        This is the current behavior and provides backwards compatibility for option (2) above.
    This proposal primarily adds the ability to have a project specific/local configuration file (3.i above). This behavior also has similar benefits as (1) in CI environments because the working directory is likely to be shared between different stages of a containerzed workflow while `$HOME` is not.
     This proposal will most likely require a flag that allows the user to specify where they want to write their config during login, `--local` would write to the working directory and when `--local=false` (the default setting) it would go the default user global config location, which is resolved as described above.

All three options can be considered independently but should also be compatible with each other.

Ultimately the goal is to provide more flexibility and control over how the CLI is working. The initial use cases I have considered deal with CI systems. But this could also allow for workflows like https://git-secret.io/

**Comment by utsavanand2** [comment]
@LucasRoesler Since there needs to be some improvement to #831 and it's not merged already. Would you like to ideally see these proposed changes in the same PR?

**Comment by LucasRoesler** [comment]
No I don't see them as incompatible, this PR is just step (0) of my proposal 😀

**Comment by utsavanand2** [comment]
@LucasRoesler I really like the approach. I wanted to give it a try. You are suggesting to use an env var OPENFAAS_CONFIG, that would work great for the config file, but we also need to make sure that the CLI is actually running in CI so that we can also modify the permissions of the shrinkwrapped build folder to something more permissive.

1.  I was thinking if we can change the permission of the build folder if the OPENFAAS_CONFIG is set to the current dir, but that doesn’t seems to be a really nice idea.

2. Or, we can still have the CI env var on top of the OPENFAAS_CONFIG var, and if the CI env var is set and the OPENFAAS_CONFIG is not set, then we can have the config as we have in the PR #831 

3. If both the CI and OPENFAAS_CONFIG env vars are set then we can have modified permissions for both the build dir and the config dir, but only the config doesn’t live in the current dir anymore but in as pointed by OPENFAAS_CONFIG env var.

**Comment by alexellis** [comment]
I would be supportive of the below with `CI` setting factored into the ordering also.

```
look for the config file in OPENFAAS_CONFIG
look for (hidden) directory .openfaas in the current directory
~~look for directory openfaas in XDG_CONFIG_HOME~~
look for the config directory ~/.openfaas
```

`~~` - XDG to be removed from the order.
