### ISSUE TITLE
why does faas deploy need to read from template directory ?

### ISSUE THREAD

**Issue by nxtcoder17** [openfaas/faas-cli#882]
## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

---

For clarity sake, i am testing it inside the openfaas-cli docker image running on my kubernetes as a Pod

![2021-04-19-160540_1920x1080_scrot](https://user-images.githubusercontent.com/22402557/115223161-2025a080-a129-11eb-8d6a-932c28b70cc4.png)

**Comment by LucasRoesler** [comment]
Hi @nxtcoder17 I am moving this to the faas-cli repo, because it fits better there. 

I did a little searching and I thought this was already reported or had some conversation but I could not find it again.

I have edited your question to insert the issue template, if you could fill it out, especially the expected behavior, it would be really helpful for anyone that else looks for this in the future.



---

Now regarding your question, there are some edge cases where the template contains metadata that is required to construct the Function deployment correctly. 

But in https://github.com/openfaas/faas-cli/pull/674 we introduced a flag `--read-template` that you can use to disable this behavior. To avoid the error, you can use

```sh
faas-cli deploy --read-template=false -f sample.yaml
```

If you have any other suggestions, please let us know.

**Comment by nxtcoder17** [comment]
Thanks @LucasRoesler, it is actually not an issue, kind of just annoying thing that's why i did not go with full blown issue format. 
I wanted to put things in a different folder structure (different from the one that comes by default in open-faas). Everything worked except the deploy threw error, as it could now find the `templates/node14/template.yml` file. 

With your solution, i am able to resolve it for now.

But, i am still guessing like, why is it looking for template.yml file anyway when i am deploying. As the only thing, deploy command has to do,  is to build the docker image with the tag given in `stack.yml` (example)  file.

**Comment by LucasRoesler** [comment]
@nxtcoder17 the main reason is for backwards compatibility with some very early workflows, perhaps it is something we could research and reconsider
