### ISSUE TITLE
Redeploying functions: Running faas-cli inside a function

### ISSUE THREAD

**Issue by MiguelBasarteJefe** [openfaas/faas-cli#919]
I'm looking for the best way run faas-cli inside a function.

## Expected Behaviour
My goal is to have a function that accepts as input the name of other functions that are already deployed an it builds and deploy those functions into the cluster. 

## Current Behaviour
I am having problems runing Docker inside an openfaas function. 

## Are you a GitHub Sponsor (Yes/No?)
- [ ] Yes
- [X] No

## List All Possible Solutions and Workarounds
I found 2 solutions to run docker inside a docker container:
- DinD: it need the --priviliged flag to access the daemon. Not supported
- DooD: it need the -v flag to mount '/var/run/docker.sock'. Not supported 

Without those flags, the function can't find the docker daemon.

Maybe there is another solution that im not taking into account. 

## Context
I am building a ci/cd enviroment and where i only update those functions that have changed since last merge. Sometimes if the pipeline fails for any reason, the function changed will be not be updated and in the next merge I have to manually make a fake change (such as a line brake) so the pipeline will build the function detecting the change. Also, sometimes the functions deployed deppends on other libraries and if the libraries change I will like to be able to update the function so it works with the updated libraries, without needing to fake a change and run trough the pipeline.

Thank you!

**Comment by welteki** [comment]
Hi @MiguelBasarteJefe

Thanks for your interest in OpenFaaS.

Take a look at the [Function Builder API](https://docs.openfaas.com/openfaas-pro/builder/) which is part of our  [OpenFaaS Pro](https://www.openfaas.com/support/) offering . I think it might be a good fit for what you are trying to do.

Han

**Comment by alexellis** [comment]
Hi @MiguelBasarteJefe as I understand it - you want to run faas-cli build from within a function?

That's not going to work because Docker cannot be packaged within the restricted security scope of a function, so will not be a supported use-case as you have outlined it.

However, as @welteki outlined, you can try our [Function Builder API](https://docs.openfaas.com/openfaas-pro/builder/) which will allow you to package a Docker context, and have it built via a HTTP API call.

Regards,

Alex
