### ISSUE TITLE
Deploy without Building

### ISSUE THREAD

**Issue by corinz** [openfaas/faas-cli#929]
Is it possible to `fass-cli deploy` without building first? I'm failing to see why the build dir is necessary for the deploy function. Especially if the container has already been pushed, all we really need is the function metadata and the image url, no?

## Expected Behaviour
`fass-cli deploy` should execute with stack.yml alone -- with no guarantees

## Current Behaviour
`fass-cli deploy` requires a build directory

Can't separate the deploy of the function from the build of the functions.

**Comment by alexellis** [comment]
Hi @corinz 

Thanks for your interest in OpenFaaS. You really do need to include an error message if you're going to raise an issue like this, rather than deleting the fields from the template that you don't want to fill in.

>  I'm failing to see why the build dir is necessary for the deploy function

Nobody said that you have to build your function before you can deploy it. As far as I'm aware that isn't the case.

I'm going to close the issue due to a lack of information, but here's me showing you a build folder isn't required:

```
 git clone https://github.com/alexellis/go-long --depth=1

cd go-long

faas-cli template pull stack

alex@m1:/tmp/go-long$ faas-cli deploy
Deploying: go-long.

Deployed. 202 Accepted.
URL: http://127.0.0.1:8080/function/go-long

Deploying: node12-sleep.

Deployed. 202 Accepted.
URL: http://127.0.0.1:8080/function/node12-sleep
```

Alex
